name: my-app
replicas: 2

image: nginx:latest

createNamespace: true
namespace: default

serviceType: LoadBalancer
servicePort: 80
serviceTargetPort: 80

env:
  config:
    key1: value1
  secrets:
    key2: value2
